// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: cart.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Cart_GetCart_FullMethodName       = "/Cart/GetCart"
	Cart_PostAddToCart_FullMethodName = "/Cart/PostAddToCart"
	Cart_GetCheckout_FullMethodName   = "/Cart/GetCheckout"
)

// CartClient is the client API for Cart service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CartClient interface {
	GetCart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MsgArrProductResp, error)
	PostAddToCart(ctx context.Context, in *MsrReqPostAddToCart, opts ...grpc.CallOption) (*DataEmpty, error)
	GetCheckout(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DataEmpty, error)
}

type cartClient struct {
	cc grpc.ClientConnInterface
}

func NewCartClient(cc grpc.ClientConnInterface) CartClient {
	return &cartClient{cc}
}

func (c *cartClient) GetCart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MsgArrProductResp, error) {
	out := new(MsgArrProductResp)
	err := c.cc.Invoke(ctx, Cart_GetCart_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartClient) PostAddToCart(ctx context.Context, in *MsrReqPostAddToCart, opts ...grpc.CallOption) (*DataEmpty, error) {
	out := new(DataEmpty)
	err := c.cc.Invoke(ctx, Cart_PostAddToCart_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartClient) GetCheckout(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DataEmpty, error) {
	out := new(DataEmpty)
	err := c.cc.Invoke(ctx, Cart_GetCheckout_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CartServer is the server API for Cart service.
// All implementations must embed UnimplementedCartServer
// for forward compatibility
type CartServer interface {
	GetCart(context.Context, *Empty) (*MsgArrProductResp, error)
	PostAddToCart(context.Context, *MsrReqPostAddToCart) (*DataEmpty, error)
	GetCheckout(context.Context, *Empty) (*DataEmpty, error)
	mustEmbedUnimplementedCartServer()
}

// UnimplementedCartServer must be embedded to have forward compatible implementations.
type UnimplementedCartServer struct {
}

func (UnimplementedCartServer) GetCart(context.Context, *Empty) (*MsgArrProductResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCart not implemented")
}
func (UnimplementedCartServer) PostAddToCart(context.Context, *MsrReqPostAddToCart) (*DataEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostAddToCart not implemented")
}
func (UnimplementedCartServer) GetCheckout(context.Context, *Empty) (*DataEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCheckout not implemented")
}
func (UnimplementedCartServer) mustEmbedUnimplementedCartServer() {}

// UnsafeCartServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CartServer will
// result in compilation errors.
type UnsafeCartServer interface {
	mustEmbedUnimplementedCartServer()
}

func RegisterCartServer(s grpc.ServiceRegistrar, srv CartServer) {
	s.RegisterService(&Cart_ServiceDesc, srv)
}

func _Cart_GetCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServer).GetCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cart_GetCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServer).GetCart(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cart_PostAddToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsrReqPostAddToCart)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServer).PostAddToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cart_PostAddToCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServer).PostAddToCart(ctx, req.(*MsrReqPostAddToCart))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cart_GetCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServer).GetCheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cart_GetCheckout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServer).GetCheckout(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Cart_ServiceDesc is the grpc.ServiceDesc for Cart service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cart_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Cart",
	HandlerType: (*CartServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCart",
			Handler:    _Cart_GetCart_Handler,
		},
		{
			MethodName: "PostAddToCart",
			Handler:    _Cart_PostAddToCart_Handler,
		},
		{
			MethodName: "GetCheckout",
			Handler:    _Cart_GetCheckout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cart.proto",
}
